version: "3"

services:
  ha-anomaly:
    build: .
    container_name: ha-anomaly-detection
    restart: unless-stopped
    volumes:
      - ./models:/app/models
      - ./config.py:/app/config.py
    environment:
      - TZ=America/Edmonton
      - LOOP_INTERVAL=900 # Run every 15 minutes (in seconds)
      - SLEEP_AFTER_ERROR=300 # Retry after 5 minutes on error
